mall/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/<int:product_pk>/add/", views.add_to_cart, name="add_to_cart"),
    path("orders/", views.order_list, name="order_list"),
    path("orders/new/", views.order_new, name="order_new"),
    path("orders/<int:pk>/pay/", views.order_pay, name="order_pay"),
    path(
        "orders/<int:order_pk>/check/<int:payment_pk>/",
        views.order_check,
        name="order_check",
    ),
    path("orders/<int:pk>/", views.order_detail, name="order_detail"),
    path("webhook/", views.portone_webhook, name="webhook"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("mall/", include("mall.urls")),
    path("mall_test/", include("mall_test.urls")),
    path("", TemplateView.as_view(template_name="root.html"), name="root"),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/models.py
import logging
from typing import List
from uuid import uuid4

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import UniqueConstraint, QuerySet
from django.http import Http404
from django.urls import reverse
from django.utils.functional import cached_property
from iamport import Iamport

from accounts.models import User


logger = logging.getLogger(__name__)


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = "상품 분류"


class Product(models.Model):
    class Status(models.TextChoices):
        ACTIVE = "a", "정상"
        SOLD_OUT = "s", "품절"
        OBSOLETE = "o", "단종"
        INACTIVE = "i", "비활성화"

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField()  # 0 포함
    status = models.CharField(
        choices=Status.choices, default=Status.INACTIVE, max_length=1
    )
    photo = models.ImageField(
        upload_to="mall/product/photo/%Y/%m/%d",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"<{self.pk}> {self.name}"

    class Meta:
        verbose_name = verbose_name_plural = "상품"
        ordering = ["-pk"]


class CartProduct(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_constraint=False,
        related_name="cart_product_set",
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    quantity = models.PositiveIntegerField(
        default=1,
        validators=[
            MinValueValidator(1),
        ],
    )

    def __str__(self):
        return f"<{self.pk}> {self.product.name} - {self.quantity}"

    @property
    def amount(self):
        return self.product.price * self.quantity

    class Meta:
        verbose_name_plural = verbose_name = "장바구니 상품"
        constraints = [
            UniqueConstraint(fields=["user", "product"], name="unique_user_product"),
        ]


class Order(models.Model):
    class Status(models.TextChoices):
        REQUESTED = "requested", "주문요청"
        FAILED_PAYMENT = "failed_payment", "결제실패"
        PAID = "paid", "결제완료"
        PREPARED_PRODUCT = "prepared_product", "상품준비중"
        SHIPPED = "shipped", "배송중"
        DELIVERED = "delivered", "배송완료"
        CANCELLED = "cancelled", "주문취소"

    uid = models.UUIDField(default=uuid4, editable=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    total_amount = models.PositiveIntegerField("결제금액")
    status = models.CharField(
        "진행상태",
        max_length=20,
        choices=Status.choices,
        default=Status.REQUESTED,
        db_index=True,
    )
    product_set = models.ManyToManyField(
        Product,
        through="OrderedProduct",
        blank=False,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self) -> str:
        return reverse("order_detail", args=[self.pk])

    def can_pay(self) -> bool:
        return self.status in (self.Status.REQUESTED, self.Status.FAILED_PAYMENT)

    def cancel(self, reason=""):
        for payment in self.orderpayment_set.all():
            payment.cancel(reason=reason)

    def update(self):
        for payment in self.orderpayment_set.all():
            payment.update()

    @property
    def name(self) -> str:
        first_product = self.product_set.first()
        if first_product is None:
            return "등록된 상품이 없습니다."
        size = self.product_set.all().count()
        if size < 2:
            return first_product.name
        return f"{first_product.name} 외 {size - 1}건"

    @classmethod
    def create_from_cart(
        cls, user: User, cart_product_qs: QuerySet[CartProduct]
    ) -> "Order":
        cart_product_list: List[CartProduct] = list(cart_product_qs)

        total_amount = sum(cart_product.amount for cart_product in cart_product_list)
        order = cls.objects.create(user=user, total_amount=total_amount)

        ordered_product_list = []
        for cart_product in cart_product_list:
            product = cart_product.product
            ordered_product = OrderedProduct(
                order=order,
                product=product,
                name=product.name,
                price=product.price,
                quantity=cart_product.quantity,
            )
            ordered_product_list.append(ordered_product)

        OrderedProduct.objects.bulk_create(ordered_product_list)

        return order

    class Meta:
        ordering = ["-pk"]
        verbose_name_plural = verbose_name = "주문"


class OrderedProduct(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    name = models.CharField("상품명", max_length=100, help_text="주문 시점의 상품명을 저장합니다.")
    price = models.PositiveIntegerField("상품가격", help_text="주문 시점의 상품가격을 저장합니다.")
    quantity = models.PositiveIntegerField("수량")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class AbstractPortonePayment(models.Model):
    class PayMethod(models.TextChoices):
        CARD = "card", "신용카드"

    class PayStatus(models.TextChoices):
        READY = "ready", "결제 준비"
        PAID = "paid", "결제 완료"
        CANCELLED = "cancelled", "결제 취소"
        FAILED = "failed", "결제 실패"

    meta = models.JSONField("포트원 결제내역", default=dict, editable=False)
    uid = models.UUIDField("쇼핑몰 결제식별자", default=uuid4, editable=False)
    name = models.CharField("결제명", max_length=200)
    desired_amount = models.PositiveIntegerField("결제금액", editable=False)
    buyer_name = models.CharField("구매자 이름", max_length=100, editable=False)
    buyer_email = models.EmailField("구매자 이메일", editable=False)
    pay_method = models.CharField(
        "결제수단", max_length=20, choices=PayMethod.choices, default=PayMethod.CARD
    )
    pay_status = models.CharField(
        "결제상태", max_length=20, choices=PayStatus.choices, default=PayStatus.READY
    )
    is_paid_ok = models.BooleanField(
        "결제성공 여부", default=False, db_index=True, editable=False
    )

    @property
    def merchant_uid(self) -> str:
        return str(self.uid)

    @cached_property
    def api(self):
        return Iamport(
            imp_key=settings.PORTONE_API_KEY, imp_secret=settings.PORTONE_API_SECRET
        )

    def update(self, response=None):
        if response is None:
            try:
                self.meta = self.api.find(merchant_uid=self.merchant_uid)
            except (Iamport.ResponseError, Iamport.HttpError) as e:
                logger.error(str(e), exc_info=e)
                raise Http404("포트원에서 결제내역을 찾을 수 없습니다.")
        else:
            self.meta = response

        self.pay_status = self.meta["status"]
        self.is_paid_ok = self.api.is_paid(self.desired_amount, response=self.meta)

        # TODO: 결제는 되었는 데, 결제금액이 맞지 않는 경우, -> 의심된다 플래그를 지정한다든지.

        self.save()

    def cancel(self, reason=""):
        try:
            response = self.api.cancel(reason, merchant_uid=self.merchant_uid)
            self.update(response)
        except Iamport.ResponseError:
            self.update()

    class Meta:
        abstract = True


class OrderPayment(AbstractPortonePayment):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, db_constraint=False)

    def update(self, response=None):
        super().update(response)

        if self.is_paid_ok:
            self.order.status = Order.Status.PAID
            self.order.save()
            # 다수의 결제시도
            self.order.orderpayment_set.exclude(pk=self.pk).delete()

        elif self.pay_status == self.PayStatus.FAILED:
            self.order.status = Order.Status.FAILED_PAYMENT
            self.order.save()

        elif self.pay_status == self.PayStatus.CANCELLED:
            self.order.status = Order.Status.CANCELLED
            self.order.save()

    @classmethod
    def create_by_order(cls, order: Order) -> "OrderPayment":
        return cls.objects.create(
            order=order,
            name=order.name,
            desired_amount=order.total_amount,
            buyer_name=order.user.get_full_name() or order.user.username,
            buyer_email=order.user.email,
        )

mall/forms.py
from django import forms
from .models import CartProduct


class CartProductForm(forms.ModelForm):
    class Meta:
        model = CartProduct
        fields = ["quantity"]

mall/views.py
import json

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import ListView

from mall.decorators import deny_from_untrusted_hosts
from mall.forms import CartProductForm
from mall.models import Product, CartProduct, Order, OrderPayment


class ProductListView(ListView):
    model = Product
    queryset = Product.objects.filter(status=Product.Status.ACTIVE).select_related(
        "category"
    )
    paginate_by = 4

    def get_queryset(self):
        qs = super().get_queryset()

        query = self.request.GET.get("query", "")
        if query:
            qs = qs.filter(name__icontains=query)

        return qs


product_list = ProductListView.as_view()


@login_required
def cart_detail(request):
    cart_product_qs = (
        CartProduct.objects.filter(
            user=request.user,
        )
        .select_related("product")
        .order_by("product__name")
    )

    CartProductFormSet = modelformset_factory(
        model=CartProduct,
        form=CartProductForm,
        extra=0,
        can_delete=True,
    )

    if request.method == "POST":
        formset = CartProductFormSet(
            data=request.POST,
            queryset=cart_product_qs,
        )
        if formset.is_valid():
            formset.save()
            messages.success(request, "장바구니를 업데이트했습니다.")
            return redirect("cart_detail")
    else:
        formset = CartProductFormSet(
            queryset=cart_product_qs,
        )

    return render(
        request,
        "mall/cart_detail.html",
        {
            "formset": formset,
        },
    )


@login_required
@require_POST
def add_to_cart(request, product_pk):
    product_qs = Product.objects.filter(
        status=Product.Status.ACTIVE,
    )
    product = get_object_or_404(product_qs, pk=product_pk)

    quantity = int(request.GET.get("quantity", 1))

    cart_product, is_created = CartProduct.objects.get_or_create(
        user=request.user,
        product=product,
        defaults={"quantity": quantity},
    )
    if not is_created:
        cart_product.quantity += quantity
        cart_product.save()

    # messages.success(request, "장바구니에 추가했습니다.")

    # redirect_url = request.META.get("HTTP_REFERER", "product_list")
    # return redirect(redirect_url)

    return HttpResponse("ok")


# Pagination 처리가 필요하시다면 ListView를 사용하세요.


@login_required
def order_list(request):
    order_qs = Order.objects.all().filter(user=request.user, status=Order.Status.PAID)
    return render(
        request,
        "mall/order_list.html",
        {
            "order_list": order_qs,
        },
    )


@login_required
def order_new(request):
    cart_product_qs = CartProduct.objects.filter(user=request.user)

    order = Order.create_from_cart(request.user, cart_product_qs)
    cart_product_qs.delete()

    return redirect("order_pay", order.pk)


@login_required
def order_pay(request, pk):
    order = get_object_or_404(Order, pk=pk, user=request.user)

    if not order.can_pay():
        messages.error(request, "현재 결제를 할 수 없는 주문입니다.")
        return redirect(order)

    payment = OrderPayment.create_by_order(order)

    check_url = reverse("order_check", args=[order.pk, payment.pk])

    payment_props = {
        "merchant_uid": payment.merchant_uid,
        "name": payment.name,
        "amount": payment.desired_amount,
        "buyer_name": payment.buyer_name,
        "buyer_email": payment.buyer_email,
        "m_redirect_url": request.build_absolute_uri(check_url),
    }

    return render(
        request,
        "mall/order_pay.html",
        {
            "portone_shop_id": settings.PORTONE_SHOP_ID,
            "payment_props": payment_props,
            "next_url": check_url,
        },
    )


@login_required
def order_check(request, order_pk, payment_pk):
    payment = get_object_or_404(OrderPayment, pk=payment_pk, order__pk=order_pk)
    payment.update()
    # return redirect(payment.order)
    return redirect("order_detail", order_pk)


@login_required
def order_detail(request, pk):
    order = get_object_or_404(Order, pk=pk, user=request.user)
    return render(
        request,
        "mall/order_detail.html",
        {
            "order": order,
        },
    )


@require_POST
@csrf_exempt
@deny_from_untrusted_hosts(settings.PORTONE_WEBHOOK_IPS)
def portone_webhook(request):
    if request.META["CONTENT_TYPE"] == "application/json":
        payload = json.loads(request.body)
        merchant_uid = payload.get("merchant_uid")
    else:
        merchant_uid = request.POST.get("merchant_uid")

    if not merchant_uid:
        return HttpResponse("merchant_uid 인자가 누락되었습니다.", status=400)
    elif merchant_uid == "merchant_1234567890":
        return HttpResponse("test ok")

    payment = get_object_or_404(OrderPayment, uid=merchant_uid)
    payment.update()

    return HttpResponse("ok")

mall/templates/mall/base.html
{% extends "base.html" %}

mall/templates/mall/cart_detail.html
{% extends "mall/base.html" %}
{% load widget_tweaks %}

{% block content %}
    <h2>장바구니</h2>

    <form action="" method="post" novalidate>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>상품명</th>
                    <th>수량</th>
                    <th>삭제여부</th>
                </tr>
            </thead>
            <tbody>
                {% csrf_token %}
                {{ formset.management_form }}
                {% for form in formset %}
                    {% for field in form.hidden_fields %}{{ field }}{% endfor %}
                    {% with form.instance as cart_product %}
                        <tr>
                            <td>{{ cart_product.product.name }}</td>

                            <td>
                                {% render_field form.quantity class+="form-control text-end" %}
                                {{ form.quantity.errors }}
                            </td>
                            <td class="text-center">{% render_field form.DELETE class+="form-check-input" %}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" class="btn btn-primary" value="장바구니 업데이트" />
    </form>

    <div class="text-end">
        <a href="{% url 'order_new' %}" class="btn btn-primary">주문하기</a>
    </div>
{% endblock %}

mall/templates/mall/order_detail.html
{% extends "mall/base.html" %}
{% load humanize %}

{% block content %}
    <h2>주문내역</h2>
    <ul>
        <li>주문번호: {{ order.uid }}</li>
        <li>{{ order.total_amount|intcomma }}원</li>
        <li>{{ order.get_status_display }}</li>
    </ul>

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>주문상품명</th>
                <th>상품가격</th>
                <th>주문수량</th>
            </tr>
        </thead>
        <tbody>
            {% for ordered_product in order.orderedproduct_set.all %}
                <tr>
                    <td>{{ ordered_product.name }}</td>
                    <td class="text-end">{{ ordered_product.price|intcomma }}</td>
                    <td class="text-end">{{ ordered_product.quantity|intcomma }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mall/templates/mall/order_list.html
{% extends "mall/base.html" %}
{% load humanize %}

{% block content %}
    <h2>주문목록</h2>

    <table class="table table-hover table-ordered">
        <thead>
            <tr>
                <th>주문명</th>
                <th>결제금액</th>
                <th>상태</th>
                <th>주문시각</th>
            </tr>
        </thead>
        <tbody>
            {% for order in order_list %}
                <tr>
                    <td>
                        <a href="{{ order.get_absolute_url }}">{{ order.name }}</a>
                    </td>
                    <td>{{ order.total_amount|intcomma }}원</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>{{ order.created_at }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mall/templates/mall/order_pay.html
{% extends "mall/base.html" %}

{% block content %}<h2>결제</h2>{% endblock %}

{% block extra-script %}
    {{ payment_props|json_script:"payment-props" }}
    <script src="https://cdn.iamport.kr/v1/iamport.js"></script>
    <script>
        (function() {
            const IMP = window.IMP;
            const next_url = "{{ next_url }}";
            IMP.init("{{ portone_shop_id }}");

            const json_string = document.querySelector("#payment-props").textContent;
            const props = JSON.parse(json_string);

            IMP.request_pay(props, function(response) {
                location.href = next_url;
            });
        })();
    </script>
{% endblock %}

mall/templates/mall/product_list.html
{% extends "mall/base.html" %}
{% load django_bootstrap5 %}
{% load humanize %}
{% load thumbnail %}

{% block content %}
    <div class="modal fade" id="alert-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">알림</h1>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'cart_detail' %}" class="btn btn-primary">장바구니 보기</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for product in product_list %}
            <div class="col-sm-6 col-lg-4 mb-3">
                <div class="card">
                    {# djlint: off #}
                    {% thumbnail product.photo "300x300" crop="center" as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.name }} 사진" class="card-img-top object-fit-cover"/>
                    {% endthumbnail %}
                    {# djlint: on #}

                    <div class="card-body">
                        {{ product.category.name }}
                        <div>
                            <h5 class="text-truncate">{{ product.name }}</h5>
                        </div>
                        <div class="d-flex justify-content-between">
                            <div>{{ product.price|intcomma }}원</div>
                            <div>
                                <a href="{% url 'add_to_cart' product.pk %}"
                                   class="btn btn-primary cart-button">장바구니에 담기</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="mt-3 mb-3">{% bootstrap_pagination page_obj url=request.get_full_path %}</div>

{% endblock %}

{% block extra-script %}
    <script>
        const alert_modal = new AlertModal("#alert-modal");

        document.querySelectorAll(".cart-button").forEach(function(button) {
            button.addEventListener("click", function(e) {
                e.preventDefault();
                const url = e.target.href;

                fetch(url, {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": window.csrf_token,
                    }
                }).then(function(response) {
                    return response.status === 200 ? response.text() : Promise.reject(response)
                }).then(function() {
                    alert_modal.show("장바구니에 담았습니다.");

                }).catch(function() {
                    alert_modal.show("장바구니에 담았습니다.");
                });
            });
        });
    </script>
{% endblock %}